name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test secrets
      run: |
        echo "PUBLIC_REPO_URL length: ${#PUBLIC_REPO_URL}"
        echo "PUBLIC_REPO_TOKEN length: ${#PUBLIC_REPO_TOKEN}"
        if [ -n "$PUBLIC_REPO_URL" ]; then
          echo "✅ PUBLIC_REPO_URL is set"
        else
          echo "❌ PUBLIC_REPO_URL is empty"
        fi
        if [ -n "$PUBLIC_REPO_TOKEN" ]; then
          echo "✅ PUBLIC_REPO_TOKEN is set"
        else
          echo "❌ PUBLIC_REPO_TOKEN is empty"
        fi
      env:
        PUBLIC_REPO_URL: ${{ secrets.PUBLIC_REPO_URL }}
        PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}