name: Public Release

on:
  push:
    tags:
      - "public-*"
      - "*-public"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Clone public repo and update
      run: |
        # Clone public repo
        git clone https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/sancovp/heaven-bml.git /tmp/public-repo
        
        # Copy all files except ideas to public repo
        rsync -av --exclude='ideas/' --exclude='.git/' . /tmp/public-repo/
        
        # Commit and push to public repo
        cd /tmp/public-repo
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add .
        git commit -m "Public release ${{ github.ref_name }}" || echo "No changes to commit"
        git push origin main
        
        # Create and push tag to trigger PyPI workflow
        VERSION=$(echo "${{ github.ref_name }}" | sed 's/public-/v/')
        git tag $VERSION
        git push origin $VERSION
      env:
        GH_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}